### ISSUE TITLE
From where can we download the pre-trained weights 

### ISSUE THREAD

**Issue by rumaima** [praveena2j/JointCrossAttentional-AV-Fusion#5]
Hi,

I need the pre-trained weights in order to run the main.py in the absence of which it throws the following error
FileNotFoundError: [Errno 2] No such file or directory: 'PretrainedWeights/Val_model_valence_cnn_lstm_mil_64_new.t7'

Could you please provide the link to download the weights.

Thank you.

**Comment by praveena2j** [comment]
Updated the trained weights  to reproduce our results
